import time

print("██╗  ██╗██╗████████╗██╗  ██╗ █████╗  ██████╗██╗  ██╗")
print("██║ ██╔╝██║╚══██╔══╝██║  ██║██╔══██╗██╔════╝██║ ██╔╝")
print("█████╔╝ ██║   ██║   ███████║███████║██║     █████╔╝ ")
print("██╔═██╗ ██║   ██║   ██╔══██║██╔══██║██║     ██╔═██╗ ")
print("██║  ██╗██║   ██║   ██║  ██║██║  ██║╚██████╗██║  ██╗")
print("╚═╝  ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝")
print("-----CRACK ver1.1 BETA")
print("")
print("")
print("")
print("Loading dll's...")
time.sleep(10)
print("")
print("Search game process...")
time.sleep(4)
print("")
print("Game process Found!")
time.sleep(4)
print("")
print("open crack...")
f = open("crack.exe")
time.sleep(2)
print("")
print("Injecting script to game process...")
time.sleep(6)
print("")
print("Done!")


